version: '3.7'
services:
  bot_tg:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: always
    container_name: bot_gpt
    volumes:
      - ./bd/:/bot/bd/base/
      - ./log/:/bot/log/