version: '3.7'
services:
  bot_tg:
    image: kureed/gpt_bot:latest
    restart: always
    container_name: bot_gpt
    volumes:
      - ./.env:/bot/.env
      - ./bd/:/bot/bd/base/
      - ./log/:/bot/log/